-- Active: 1743824447804@@127.0.0.1@3306
-- Tabela: user
CREATE DATABASE quiz_math;

USE quiz_math;

CREATE TABLE user (
  id_user INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(20) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(150) NOT NULL,
  xp INT DEFAULT 0,
  is2fa BOOLEAN DEFAULT FALSE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tabela: Quest
CREATE TABLE Quest (
  id_quest INT PRIMARY KEY AUTO_INCREMENT,
  image TEXT,
  texto TEXT NOT NULL,
  answers JSON NOT NULL,
  correct_answer_index CHAR(1) NOT NULL,
  peso INT NOT NULL
);

-- Tabela: QuizDefault
CREATE TABLE QuizDefault (
  id_quiz_attempt INT PRIMARY KEY AUTO_INCREMENT,
  score INT NOT NULL,
  duration INT NOT NULL,
  id_user INT NOT NULL,
  totalQuestions INT DEFAULT 20,
  correctAnswers INT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (id_user) REFERENCES user(id_user)
);
